# Generated by Django 4.0.2 on 2022-03-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0002_remove_createuser_is_owner_createuser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='createuser',
            name='is_owner',
            field=models.BooleanField(default=False, verbose_name='is_owner'),
        ),
    ]
