# Generated by Django 4.0.2 on 2022-03-16 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0003_createuser_is_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_registration',
            name='NID_photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_nid'),
        ),
        migrations.AlterField(
            model_name='user_registration',
            name='User_image',
            field=models.ImageField(blank=True, null=True, upload_to='user_pics'),
        ),
    ]
